dist: xenial
sudo: false
language: python
python: 3.6
cache:
- pip
- directory:
  - .tox/dist
  - .tox/distshare
env:
- TOX_ENV=docs
- TOX_ENV=flake8
- TOX_ENV=py27
- TOX_ENV=py34
- TOX_ENV=py35
- TOX_ENV=py36
- TOX_ENV=py37
- TOX_ENV=py38
- TOX_ENV=pypy
install:
- pip install -r tests/requirements.txt
- pip install coveralls flake8 tox
- pip install -U -e .
script:
- tox -e $TOX_ENV
after_success:
- coveralls
- pip install codecov
- codecov
before_deploy: "python setup.py sdist bdist_wheel"
deploy:
  provider: releases
  api_key:
    secure: DmqlCoHxPh5465T5DQgdFE7Peqy7MVF034n7t/hpV2Lf4LH9fHUo2r1dpICpBIxRuDNCXtM3PJLk59OMqCchpcAlC7VkH6dTOLpigk/IXYtlJVr3cXQUEC0gmPuFsrZ/fpWUR0PBfUD/fBA0RW64xFZ6ksfc+76tdQrKj1appz0=
  file: dist/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: WoLpH/python-progressbar
