language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements_test.txt

before_script: flake8 --ignore=W391 progressbar tests

# command to run tests
script:
    - python setup.py test

after_success:
    - coveralls

