dist: xenial
sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- pypy
install:
- pip install .
- pip install -r tests/requirements.txt
before_script: flake8 progressbar tests examples
script:
- python setup.py test
- python examples.py
after_success:
- coveralls
- pip install codecov
- codecov
before_deploy: "python setup.py sdist bdist_wheel"
deploy:
  provider: releases
  api_key:
    secure: DmqlCoHxPh5465T5DQgdFE7Peqy7MVF034n7t/hpV2Lf4LH9fHUo2r1dpICpBIxRuDNCXtM3PJLk59OMqCchpcAlC7VkH6dTOLpigk/IXYtlJVr3cXQUEC0gmPuFsrZ/fpWUR0PBfUD/fBA0RW64xFZ6ksfc+76tdQrKj1appz0=
  file: dist/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: WoLpH/python-progressbar
